title: Stuck's Website
url: "https://s7uck.github.io"

kramdown:
  input: GFM
  hard_wrap: false

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      links:
        showcase: "/showcase"
        posts: "/posts"
        gallery: "/gallery"
        setup: "/setup"
  - scope:
      path: "photos"
    values:
      noheader: true
