title: Stuck's Website
baseurl: ""
url: "https://s7uck.github.io"

kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
collections:
  - projects
defaults:
  - scope:
      path: ""
    values:
      links:
        showcase: "/showcase"
        posts: "/posts"
        gallery: "/gallery"
        setup: "/setup"