title: Stuck's Website
url: "https://s7uck.github.io"

kramdown:
  input: GFM
  hard_wrap: false

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      links:
        showcase: "/showcase"
        posts: "/posts"
        gallery: "/gallery"
        setup: "/setup"
  - scope:
      path: "photos"
    values:
      noheader: true

include: ["_*.JPG", "_*.jpg", "_*.webp"]
webp:
  enabled: true
  quality: 90
  img_dir: ["/photos"]
  nested: true
  formats: [".JPG", ".jpg", ".jpeg"]
  append_ext: true