title: Stuck's Website
baseurl: ""
url: "https://s7uck.github.io"

kramdown:
  input: GFM
  hard_wrap: false
plugins_dir:
  - jekyll-feed
collections:
  projects:
    output: true
  photos:
    output: true
defaults:
  - scope:
      path: ""
    values:
      links:
        showcase: "/showcase"
        posts: "/posts"
        gallery: "/gallery"
        setup: "/setup"
  - scope:
      type: "photos"
    values:
      noheader: true