title: Stuck's Website
url: "https://s7uck.github.io"

kramdown:
  input: GFM
  hard_wrap: false

collections:
  projects:
    output: true

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      links:
        gallery: "/gallery"
        setup: "/setup"
#        showcase: "/showcase"
#        posts: "/posts"
  - scope:
      path: "photos"
    values:
      noheader: true

include: ["_*.JPG", "_*.jpg", "_*.webp"]
